services:
  bot-menu:
    build: .
    container_name: bot-menu-whatsapp
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./auth_info_baileys:/app/auth_info_baileys
      - ./auth_info_cliente_ncr:/app/auth_info_cliente_ncr

